;LENGUAJES Y AUTOMATAS II
;HECHO POR YOARY ANSELMO AGUILAR MATOS
;FECHA: 13 DE MAYO DEL 2019 

;OPERACIONES CON DOS NUMEROS

.MODEL SMALL
.STACK 150 

.DATA
MSJ1 DB 'NUMERO 1: ','$'
MSJ2 DB 13,10,'NUMERO 2: ','$'
MSJ3 DB 13,10,'SUMA: ','$'
MSJ4 DB 13,10,'RESTA: ','$'
MSJ5 DB 13,10,'MULTIPLICACION: ','$'
MSJ6 DB 13,10,'DIVISION: ','$'
LINEA DB 13,10,'$'
VAR1 DB 0
VAR2 DB 0 

.CODE
.STARTUP

CALL LIMPIA
MOV AH,09H
LEA DX, MSJ1 ;DESPLEGAR NUMERO 1:
INT 21H

CALL LEER ;LEE PRIMER NUMERO
SUB AL,30H ;RESTAR 30H PARA OBTENER EL NUMERO
MOV VAR1,AL ;LO GUARDO EN VAR1
MOV AH,09H
LEA DX, MSJ2 ;DESPLEGAR NUMERO 2:
INT 21H

CALL LEER ;LEE SEGUNDO NUMERO
SUB AL,30H ;RESTAR 30H PARA OBTENER SEGUNDO VALOR
MOV VAR2,AL ;GUARDAR EN VAR2
MOV BL,VAR2 ;MOVER A BL

;SUMA
ADD BL,VAR1 ; REALIZO LA SUMA DE VAR2(BL) Y VAR1 Y EL RESULTADO QUEDA EN BL
MOV AH,09H
LEA DX,MSJ3 ;IMPRIMIR SUMA
INT 21H
MOV DL,BL ;PONGO EN DL EL NUMERO A IMPRIMIR VAR2(BL)
ADD DL,30H ; AGREGO 30H PARA OBTENER EL CARACTER    
MOV AH,02H ;IMPRIME UN CARACTER
INT 21H

;RESTA
MOV BL,VAR1
SUB BL,VAR2
MOV AH,09H
LEA DX,MSJ4 ;DESPLEGAR RESTA:
INT 21H
MOV DL,BL ;MOVER RESTA A DL PARA IMPRIMIR
ADD DL,30H ;SUMAR 30 PARA OBTENER CARACTER
MOV AH,02H ;IMPRIMIR UN CARACTER
INT 21H

;MULTIPLICACION
MOV AH,09H
LEA DX,MSJ5 ;DESPLEGAR MULT
INT 21H

MOV AL,VAR1 
MOV BL,VAR2
MUL BL ;MULT AL=AL*BL
MOV DL,AL ;MOVER AL A DL PARA IMPRIMIR
ADD DL,30H ;SUMAR 30 PARA OBTENER CARACTER
MOV AH,02H ;IMPRIMIR CARACTER
INT 21H

;DIVISION
MOV AH,09H
LEA DX,MSJ6 ;DESPLEGAR DIV
INT 21H
XOR AX,AX ;LIMPIAMOS EL REGISTRO AX. 
MOV AL,VAR2
MOV BL,AL
MOV AL,VAR1
DIV BL ; DIVIDE AX/BX EL RESULTADO LO ALMACENA EN AX, EL RESIDUO QUEDA EN DX
MOV BL,AL
MOV DL,BL
ADD DL,30H
MOV AH,02H
INT 21H
.EXIT

;PROCEDIMIENTOS
SALTO PROC NEAR
MOV AH,09H
LEA DX,LINEA
INT 21H
MOV DL,00H
RET
SALTO ENDP

LEER PROC NEAR
MOV AH,01H;LEER CARACTER DESDE EL TECLADO
INT 21H;LEE PRIMER CARACTER
RET
LEER ENDP

LIMPIA PROC NEAR
MOV AH,00H
MOV AL,03H
INT 10H
RET
LIMPIA ENDP
END
